development:
  adapter: postgresql
  encoding: unicode
  database: nanotwitter_dev
  pool: 8

test:
  adapter: postgresql
  encoding: unicode
  database: nanotwitter_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: nanotwitter_prod
  pool: 8
  username: nwcyukwxqkvtpa
  password: e203afbc26a2b7e8f7feb0071f0a8487c57112d7c6526476cbc5c221fbf40411